# Generated by Django 4.2 on 2023-04-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='text',
            new_name='p1',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='p2',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='p3',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='p4',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
