# Generated by Django 4.2 on 2023-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('works', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('clients', models.IntegerField()),
                ('awards', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
