# Generated by Django 4.2 on 2023-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact_text',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=' ', upload_to='media/Settings/logo'),
            preserve_default=False,
        ),
    ]
